#' Information for a base model for correlation matrices
#' @description
#' The `basepcor` class contain a correlation matrix `base`,
#' the parameter vector `theta`, that generates
#' or is generated by `base`, the dimension `p`,
#' the index `itheta` for `theta` in the (lower) Cholesky,
#' and the Hessian around it `I0`, see details.
setClass(
  "basepcor",
  slots = c("base", "theta", "p", "itheta", "iparams", "iunknown"),
  validity = function(object) {
    (object$p>1) &&
      (object$p == nrow(object$base)) &&
      all.equal(object$base == t(object$base)) &&
      all(diag(object$base==1)) &&
      all(diag(chol(object$base))>0)
  }
)
#' @describeIn basepcor
#' Build a `basepcor` object.
#' @param base matrix (or numeric vector) as the base correlation
#' (or parameter value at the base model).
#' @param p integer (needed if `base` is vector): the dimension.
#' @param itheta integer vector or 'graphpcor' to specify the (vectorized)
#' position where 'theta' is placed in the initial (before the fill-in)
#' Cholesky (lower triangle) factor. If missing, default, assumes
#' the dense case as `itheta = which(lower.tri(...))`, giving
#' `length(theta)=p(p-1)/2`.
#' @param d0 numeric vector to specify the diagonal of the
#' Cholesky factor for the initial precision matrix `Q0`.
#' Default, if not provided, is `d0 = p:1`.
#' @param iparams integer ordered vector with length equal
#' the number of parameters used to specify common parameter values.
#' If missing, assumed to be `1:length(theta)`. Example: By setting
#' `iparams = c(1,1,2,3)` the first and second parameters are
#' considered to be the same.
#' @param iunknown integer vector to specify which correlation
#' parameters are treated as unknown when computing the Hessian.
#' Example: if `iparams = c(1,1,2,3)` and
#' `iunknown = 2:3`, the first parameter is considered
#' fixed and the Hessian will be with respect the
#' second and third parameters. If all the parameters
#' are fixed, the Hessian is then `NULL`.
#' By default all correlation parameters are treated as unknown.
#' @details
#' The Inverse Transform Parametrization - ITP,
#' is applied by starting with a
#' \deqn{\mathbf{L}^{(0)} = \left[ \begin{array}{ccccc}
#' \textrm{p} & 0 & 0 & \ldots & 0 \\
#' \theta_1 & \textrm{p-}1 & 0 & \ldots & 0 \\
#' \theta_2 & \theta_p & \textrm{p-}2 & \ddots & \vdots \\
#' \vdots & \vdots & \ddots & \ddots & 0 \\
#' \theta_{p-1} & \theta_{2p-3} & \ldots & \theta_m & 1
#' \end{array}\right] .}
#'
#' Then compute \eqn{\mathbf{Q}^{(0)}} =
#' \eqn{\mathbf{L}\mathbf{L}^{T}},
#' \eqn{\mathbf{V}^{(0)}} = \eqn{(\mathbf{Q}^{(0)})^{-1}} and
#' \eqn{s_{i}^{(0)}} = \eqn{\sqrt{\mathbf{V}_{i,i}^{(0)}}}, and
#' define \eqn{\mathbf{S}^{(0)}} = diag\eqn{(s_1^{(0)},\ldots,s_p^{(0)})}
#'  in order to have \eqn{\mathbf{C}}=
#'  \eqn{\mathbf{S}^{-1}\mathbf{V}^{(0)}\mathbf{S}^{-1}}.
#'
#' The decomposition of the Hessian matrix around the base model,
#' `I0`, formally \eqn{\mathbf{I}(\theta_0)}, is numerically computed.
#' This element has the following attributes:
#' 'h.5' as \eqn{\mathbf{I}^{1/2}(\theta_0)}, and
#' 'hneg.5' as \eqn{\mathbf{I}^{-1/2}(\theta_0)}.
#' @returns a basepcor object
#' @export
basepcor <- function(
    base,
    p,
    itheta,
    d0,
    iparams,
    iunknown) {
  UseMethod("basepcor")
}
#' @describeIn basepcor
#' Build a `basepcor` from the parameter vector.
#' @returns a `basepcor` object
#' @export
#' @example demo/basepcor.R
basepcor.numeric <- function(
    base,
    p,
    itheta,
    d0,
    iparams,
    iunknown) {

  theta <- base

  ## check p and itheta
  itheta <- p_itheta_fncheck(p, itheta)
  if(missing(p)) {
    p <- attr(itheta, "p")
  }
  stopifnot(p>1)

  m <- length(itheta)
  ## check iparams
  iparams <- m_iparams_fncheck(m, iparams)

  if(missing(d0)) {
    d0 <- p:1
  } else {
    stopifnot(all(d0>0))
  }

  ## check iunknown
  if(missing(iunknown)) {
    iunknown <- 1:length(theta)
  } else {
    stopifnot(all(iunknown %in% (1:length(theta))))
  }
  nUnk <- length(iunknown)

  ## compute L0
  L0 <- Lprec0(
    theta = theta[iparams],
    p = p,
    itheta = itheta,
    d0 = d0
  )
  lq02cor <- function(l) {
    cov2cor(chol2inv(t(l)))
  }

  ## compute the base correlation matrix
  base <- lq02cor(L0)
  U0correl <- chol(base)

  ## output
  out <- list(
    base = base,
    theta = theta,
    p = p,
    d0 = d0,
    itheta = itheta,
    iparams = iparams,
    iunknown = iunknown,
    L0 = L0, ## initial precision (lower) Cholesky
    L = t(U0correl)) ## the correlation's (lower) Cholesky
  class(out) <- "basepcor"

  return(out)
}

#' @describeIn basepcor
#' Build a `basepcor` from a correlation matrix.
#' @export
basepcor.matrix <- function(
    base,
    p,
    itheta,
    d0,
    iparams,
    iunknown) {
  stopifnot(all.equal(base, t(base)))
  p <- as.integer(nrow(base))
  if(missing(d0)) {
    d0 <- p:1
  }
  stopifnot((length(d0)==p) && (all(d0>0)))
  U0correl <- chol(base)
  Q <- chol2inv(U0correl)
  ilQ <-  which(
    lower.tri(matrix(1, p, p)) &
      (!is.zero(Q, tol = 0.001)))
  itheta <- p_itheta_fncheck(p, itheta)
  stopifnot(all(ilQ %in% itheta))

  ## compute theta
  LQ0 <- t(chol(Q))
  for(i in 1:p) {
      LQ0[i, ] <- (d0[i]/LQ0[i, i]) * LQ0[i, ]
  }
  theta <- LQ0[itheta]

  ## check iparams
  m <- length(theta)
  iparams <- m_iparams_fncheck(m, iparams)

  if(iparams[m]<m) {
    ## Check if the parameters assumed to be common actually are
    stheta <- split(theta, iparams)
    theta.diff <- all(sapply(stheta, function(x)
      all(abs(x-mean(x)))>0.001))
    if(any(theta.diff)) {
      cat("Differences found among supposed equal parameters:\n")
      print(stheta[which(theta.diff)])
      stop("Please review `iparams` definition!")
    }
    theta0 <- sapply(stheta, mean)
  } else {
    theta0 <- theta
  }
  m0 <- length(theta0)

  ## check iunknown
  if(missing(iunknown)) {
    iunknown <- 1:m0
  } else {
    stopifnot(all(iunknown %in% (1:m0)))
  }
  nUnk <- length(iunknown)

  ## Hessian around theta
  lq02cor <- function(l) {
    cov2cor(chol2inv(t(l)))
  }

  ## output
  out <- list(
    base = base,
    theta = theta,
    p = p,
    d0 = d0,
    itheta = itheta,
    iparams = iparams,
    iunknown = iunknown,
    L0 = LQ0, ## initial precision (lower) Cholesky
    L = t(U0correl)) ## the correlation's (lower) Cholesky

  class(out) <- "basepcor"

  return(out)
}
#' @describeIn basepcor
#' Print method for 'basepcor'
#' @param x a basepcor object.
#' @param ... further arguments passed on.
#' @export
print.basepcor <- function(x, ...) {
  cat("Parameters:\n", sep = "")
  print(x$theta, ...)
  cat("Base correlation matrix:\n")
  print(x$base, ...)
}

